[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    ESP32Servo
    TM1637TinyDisplay
    knolleary/PubSubClient
    beegee-tokyo/DHT sensor library for ESPx
    madhephaestus/ESP32Servo
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    Chirale_TensorFlowLite
    
board_build.partitions = huge_app.csv